### ISSUE TITLE
Wrong requeriments.txt

### ISSUE THREAD

**Issue by TagorePde** [MengWoods/PDFmanipulation#6]
I think you uploaded the wrong version of the requeriments.txt .. for example, i think actionlib is not needed and also gives error.
Regards.

**Comment by MengWoods** [comment]
Thanks for the heads up. I am figuring out it.
Would you try with the `venv` environment? It works for me.
Regards.

**Comment by MengWoods** [comment]
Hi, 
I updated the `requirements.txt` file, now it should work. The pip freeze included all of my background libs and some of them raised issue.
Let me know if you have an issue, thanks!

**Comment by TagorePde** [comment]
Perfect now !! we can close this issue.
thanks for your nice work.
Regards.
